language: node_js
node_js:
- '4'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_ec0ab0a2bdf9_key -iv $encrypted_ec0ab0a2bdf9_iv
  -in .travis/id_rsa.enc -out ~\/.ssh/id_rsa -d

- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "HunterMz"
- git config --global user.email "Hunter_Mz@icloud.com"
- git clone git@github.com:HunterMz/hexo-theme-next.git themes/next
- npm install -g hexo-cli
install:
- npm install
script:
- hexo generate
after_success:
- hexo deploy
